
[config]

  # rclone程序及配置位置
rclonefile = "/usr/bin/rclone"
rcloneconfig="/root/.config/rclone/rclone.conf"
# 保存到哪个远程盘，配置中标签名
rclonelable=""
# 备份到盘里哪个目录
bak2path="/bak/"
    # 备份时用于区别的名称
machine = ""
  # 临时目录，可选配置
#tmppath="/opt/"

[file]

#待备份文件清单列表，内容为一行一个文件(夹)，文件名内如有空格请前后加上"，可以用*指代一些文件，可在最前加#注释
#"/share/Web/qqOne Bot/" --exclude="/share/Web/qqOne Bot/"*.db
#程序将一行一行拼凑成 tar -rPvf ${tmpfile} /var/www/html/ --exclude=/var/www/html/data/*db 这样一条命令来打包

/var/www/html/.htaccess
/var/www/html/
